package com.google.assistant.actions

const val ANDROID_ACTION_VIEW_DEFAULT_INTENT = "android.intent.action.VIEW"
const val ACTIONS_BUILT_IN_INTENT_RESERVED_NAMESPACE = "actions.intent"
const val BII_INTENT_PARAMETER_MIME_TYPE = "text/*"
const val SLICE_FULFILLMENT = "actions.fulfillment.SLICE"
const val AT_URL_FULFILLMENT = "{@url}"
const val REQUIRED_FOREGROUND_ACTIVITY_KEY = "requiredForegroundActivity"
const val SAME_AS_KEY = "sameAs"

const val DEFAULT_INTENT_NAME = "YOUR_INTENT_NAME"
const val DEFAULT_INTENT_PARAMETER = "YOUR_INTENT_PARAMETER"
const val DEFAULT_PARAMETER_NAME = "YOUR_PARAMETER_NAME"
const val DEFAULT_MIME_TYPE = "YOUR_MIME_TYPE"
const val DEFAULT_SHORTCUT_SHORT_LABEL = "YOUR_SHORTCUT_SHORT_LABEL"
const val DEFAULT_PARAMETER_BINDING_KEY = "YOUR_PARAMETER_BINDING_KEY"
const val DEFAULT_PARAMETER_BINDING_VALUE = "YOUR_PARAMETER_BINDING_VALUE"
